In [1]:
import torch
import torch.nn as nn

In [2]:
prediction = torch.randn(4, 5)
label = torch.randn(4, 5)

In [3]:
print(prediction)
print('\n')
print(label)

tensor([[ 0.6789, -1.2711, -0.5721, -0.4609, -0.3288],
        [-0.4203, -0.7347, -1.1309,  0.1042, -1.2596],
        [ 0.2124, -0.3272,  1.3425, -0.9413, -0.0554],
        [-0.4848,  0.0725, -1.4071, -1.1779,  0.1715]])


tensor([[ 0.7154,  1.5164, -0.0756,  0.4718,  0.5975],
        [-0.1978,  1.3222,  0.4287,  0.2793, -0.3703],
        [-0.3824, -0.6829,  2.0001, -0.6077, -0.4347],
        [ 2.6282, -0.9899, -1.5219,  0.2074,  0.7693]])


In [4]:
mse = nn.MSELoss(reduction = 'none')
loss = mse(prediction, label)
loss

tensor([[1.3291e-03, 7.7699e+00, 2.4653e-01, 8.6987e-01, 8.5801e-01],
        [4.9511e-02, 4.2308e+00, 2.4323e+00, 3.0663e-02, 7.9100e-01],
        [3.5380e-01, 1.2654e-01, 4.3244e-01, 1.1128e-01, 1.4385e-01],
        [9.6905e+00, 1.1287e+00, 1.3165e-02, 1.9191e+00, 3.5732e-01]])

In [5]:
mse = nn.MSELoss(reduction = 'sum')
loss = mse(prediction, label)
loss

tensor(31.5565)

In [6]:
mse = nn.MSELoss(reduction = 'mean')
loss = mse(prediction, label)
loss

tensor(1.5778)

In [7]:
((prediction-label)**2).mean()

tensor(1.5778)

In [8]:
label = torch.zeros(4, 5).random_(0, 2)

In [9]:
bce = nn.BCELoss(reduction='mean')
bce(torch.sigmoid(prediction), label)

tensor(0.8175)

In [10]:
bces = bce = nn.BCEWithLogitsLoss(reduction='mean')
bces(prediction, label)

tensor(0.8175)

In [11]:
import numpy as np
x = prediction.numpy()
y = label.numpy()

In [12]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [13]:
print(x)
print('\n')
print(sigmoid(x))

[[ 0.67890394 -1.2710774  -0.5721084  -0.46089864 -0.3287971 ]
 [-0.42027983 -0.7346976  -1.130882    0.10417359 -1.259642  ]
 [ 0.21242459 -0.32715318  1.3425161  -0.9413149  -0.05539569]
 [-0.48479018  0.07254702 -1.4071175  -1.177907    0.17154633]]


[[0.66349405 0.21907288 0.36075047 0.38677266 0.41853333]
 [0.3964498  0.32416472 0.24399836 0.5260199  0.22103554]
 [0.55290735 0.41893345 0.7929034  0.28063482 0.48615465]
 [0.38112167 0.5181288  0.19668911 0.23542872 0.5427817 ]]


In [14]:
x = sigmoid(x)

In [15]:
loss_values = []
for i in range(len(y)):
    batch_loss = []
    for j in range(len(y[0])):
        if y[i][j] == 1:
            loss = -np.log(x[i][j])
        else:
            loss = -np.log(1 - x[i][j])
        batch_loss.append(loss)
        
    loss_values.append(batch_loss)

print(np.mean(loss_values))

0.81747085
