In [1]:
import torch

## **Torch Tensors**

In [2]:
# This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
# This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [4]:
# The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
# Get the number of rows of b
print(b.shape[0])

4


In [6]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do 
# c = torch.tensor([2,2,1], dtype=torch.double)

In [7]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do 
# d = torch.tensor([[2,2,1]], dtype=torch.double)

In [8]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [9]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [10]:
print(c.mean())

tensor(2.5833)


In [11]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [12]:
print(c.std())

tensor(1.5050)


In [13]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [14]:
# Reshape b
# Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
# Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
# We can reshape 3D tensors
print('\n')
# Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
three_dim = torch.rand(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12)) # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[0.6375, 0.2478, 0.7965, 0.4471],
         [0.5931, 0.4425, 0.8199, 0.1396],
         [0.9459, 0.2492, 0.0762, 0.0984]],

        [[0.3010, 0.3982, 0.1211, 0.2270],
         [0.5849, 0.5155, 0.8925, 0.4664],
         [0.3453, 0.8298, 0.1474, 0.9502]]])
tensor([[0.6375, 0.2478, 0.7965, 0.4471, 0.5931, 0.4425, 0.8199, 0.1396, 0.9459,
         0.2492, 0.0762, 0.0984],
        [0.3010, 0.3982, 0.1211, 0.2270, 0.5849, 0.5155, 0.8925, 0.4664, 0.3453,
         0.8298, 0.1474, 0.9502]])
tensor([[0.6375, 0.2478, 0.7965, 0.4471, 0.5931, 0.4425, 0.8199, 0.1396, 0.9459,
         0.2492, 0.

In [15]:
# Create a matrix with random numbers between 0 and 1
