In [2]:
import torch

## **Torch Tensors**

In [3]:
# This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [4]:
# This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [5]:
# The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [6]:
# Get the number of rows of b
print(b.shape[0])

4


In [7]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do 
# c = torch.tensor([2,2,1], dtype=torch.double)

In [8]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do 
# d = torch.tensor([[2,2,1]], dtype=torch.double)

In [9]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [10]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [11]:
print(c.mean())

tensor(2.5833)


In [12]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [13]:
print(c.std())

tensor(1.5050)


In [14]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [15]:
# Reshape b
# Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
# Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
# We can reshape 3D tensors
print('\n')
# Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
three_dim = torch.rand(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12)) # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[0.7251, 0.9909, 0.7121, 0.3355],
         [0.5267, 0.3191, 0.5929, 0.4100],
         [0.8279, 0.2766, 0.7391, 0.3143]],

        [[0.0492, 0.7503, 0.2897, 0.5495],
         [0.9305, 0.6490, 0.7329, 0.3456],
         [0.9857, 0.4781, 0.1052, 0.6298]]])
tensor([[0.7251, 0.9909, 0.7121, 0.3355, 0.5267, 0.3191, 0.5929, 0.4100, 0.8279,
         0.2766, 0.7391, 0.3143],
        [0.0492, 0.7503, 0.2897, 0.5495, 0.9305, 0.6490, 0.7329, 0.3456, 0.9857,
         0.4781, 0.1052, 0.6298]])
tensor([[0.7251, 0.9909, 0.7121, 0.3355, 0.5267, 0.3191, 0.5929, 0.4100, 0.8279,
         0.2766, 0.

In [16]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.1331, 0.2692, 0.3185, 0.6862],
        [0.1043, 0.0078, 0.5638, 0.0779],
        [0.5242, 0.3121, 0.7390, 0.9259],
        [0.8465, 0.9147, 0.7398, 0.2943]])


In [17]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn (4,4)
print (r2)
print (r2.dtype)

tensor([[ 2.5460,  0.2488,  0.5654, -0.1609],
        [ 1.4123, -1.2645,  2.3333,  1.3248],
        [-0.5947,  0.3223, -0.6366, -1.0071],
        [-0.8537, -1.5029, -0.3233, -0.5711]])
torch.float32


In [18]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint (6,10, (5,))
print (in_array)
print (in_array.dtype)

tensor([6, 8, 6, 8, 8])
torch.int64


In [19]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print (in_array2)

tensor([[6, 6, 8],
        [9, 9, 6],
        [8, 7, 8]])


In [20]:
#Get the number of elemens in in_array
print(torch.numel(in_array))
#Get the number of elemens in in_array2
print(torch.numel(in_array2))

5
9


In [21]:
#Construct a 3x3 matrix of zeros and of atype long:
z = torch.zeros (3, 3, dtype=torch.long)
print (z)
#Construct a 3x3 matrix of ones
o = torch.ones (3,3)
print(o)
print (o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [22]:
r2_like = torch.randn_like(r2, dtype=torch.double)  # Convert the data type of the tensor to double
print(r2_like)

tensor([[-0.8862,  0.1193, -0.6265,  0.5972],
        [-0.1688,  1.1153, -0.2220, -0.2192],
        [ 0.6073,  1.5963,  0.9287,  1.0005],
        [ 0.9016,  0.0061, -0.2399,  1.0207]], dtype=torch.float64)


In [23]:
# Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 2.6791,  0.5180,  0.8838,  0.5253],
        [ 1.5166, -1.2567,  2.8971,  1.4027],
        [-0.0706,  0.6343,  0.1024, -0.0812],
        [-0.0072, -0.5882,  0.4165, -0.2769]])


In [24]:
# In-place addition (change the value of r2)
r2.add_(r)
print(r2)

tensor([[ 2.6791,  0.5180,  0.8838,  0.5253],
        [ 1.5166, -1.2567,  2.8971,  1.4027],
        [-0.0706,  0.6343,  0.1024, -0.0812],
        [-0.0072, -0.5882,  0.4165, -0.2769]])


In [25]:
print(r2[:, 1])
print(r2[:, 2])
print(r2[:3, :])
num_ten = r2[2, 3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([ 0.5180, -1.2567,  0.6343, -0.5882])
tensor([0.8838, 2.8971, 0.1024, 0.4165])
tensor([[ 2.6791,  0.5180,  0.8838,  0.5253],
        [ 1.5166, -1.2567,  2.8971,  1.4027],
        [-0.0706,  0.6343,  0.1024, -0.0812]])
tensor(-0.0812)
-0.08115077018737793
tensor([-0.0706,  0.6343,  0.1024, -0.0812])


## **Numpy Bridge**

In [26]:
import numpy as np

In [27]:
# Converting a Torch Tensor to a Numpy Array
print(a)
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
# See how the numpy array changes in value when changing the tensor.
a.add_(1)
print(a)
print(b)

tensor([2, 2, 1])
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
# Converting NumPy Array to Torch Tensor
# See how changing the numpy array changed the Torch tensor automatically.
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [29]:
# Move the tensors to GPU if available
r2 = r2.cuda()
print(r2)

AssertionError: Torch not compiled with CUDA enabled