In [1]:
import torch

## **Torch Tensors**

In [2]:
# This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
# This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [4]:
# The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
# Get the number of rows of b
print(b.shape[0])

4


In [6]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do 
# c = torch.tensor([2,2,1], dtype=torch.double)

In [7]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do 
# d = torch.tensor([[2,2,1]], dtype=torch.double)

In [8]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [9]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [10]:
print(c.mean())

tensor(2.5833)


In [11]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [12]:
print(c.std())

tensor(1.5050)


In [13]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [14]:
# Reshape b
# Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
# Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
# We can reshape 3D tensors
print('\n')
# Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
three_dim = torch.rand(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12)) # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[0.5438, 0.1058, 0.0105, 0.7233],
         [0.4742, 0.5535, 0.1178, 0.8932],
         [0.4585, 0.3730, 0.7157, 0.6798]],

        [[0.0417, 0.7883, 0.4879, 0.8161],
         [0.0173, 0.5225, 0.3910, 0.6215],
         [0.2771, 0.4059, 0.7916, 0.4794]]])
tensor([[0.5438, 0.1058, 0.0105, 0.7233, 0.4742, 0.5535, 0.1178, 0.8932, 0.4585,
         0.3730, 0.7157, 0.6798],
        [0.0417, 0.7883, 0.4879, 0.8161, 0.0173, 0.5225, 0.3910, 0.6215, 0.2771,
         0.4059, 0.7916, 0.4794]])
tensor([[0.5438, 0.1058, 0.0105, 0.7233, 0.4742, 0.5535, 0.1178, 0.8932, 0.4585,
         0.3730, 0.

In [15]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.1188, 0.4097, 0.6822, 0.6564],
        [0.9624, 0.8701, 0.4617, 0.7332],
        [0.6793, 0.6975, 0.8906, 0.4916],
        [0.1104, 0.5228, 0.4519, 0.5933]])


In [16]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn (4,4)
print (r2)
print (r2.dtype)

tensor([[ 0.6307, -0.2935,  1.3142,  0.1904],
        [ 0.3847,  0.6459, -0.3631,  1.0207],
        [ 1.3641,  0.1584,  1.6945, -1.1935],
        [-0.6092,  1.0178,  0.3012,  0.5383]])
torch.float32


In [17]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint (6,10, (5,))
print (in_array)
print (in_array.dtype)

tensor([7, 7, 8, 7, 8])
torch.int64


In [18]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print (in_array2)

tensor([[6, 7, 9],
        [9, 6, 9],
        [7, 9, 9]])


In [19]:
#Get the number of elemens in in_array
print(torch.numel(in_array))
#Get the number of elemens in in_array2
print(torch.numel(in_array2))

5
9


In [20]:
#Construct a 3x3 matrix of zeros and of atype long:
z = torch.zeros (3, 3, dtype=torch.long)
print (z)
#Construct a 3x3 matrix of ones
o = torch.ones (3,3)
print(o)
print (o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [21]:
r2_like = torch.randn_like(r2, dtype=torch.double)  # Convert the data type of the tensor to double
print(r2_like)

tensor([[-1.1081, -0.0111, -1.2467, -0.0228],
        [ 0.2485,  1.0454, -1.3260,  0.0305],
        [-0.4554,  0.7623, -1.0623, -1.0449],
        [-0.4053, -1.2672, -0.6121, -0.5626]], dtype=torch.float64)


In [22]:
# Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 0.7495,  0.1162,  1.9964,  0.8468],
        [ 1.3471,  1.5161,  0.0986,  1.7539],
        [ 2.0434,  0.8559,  2.5851, -0.7019],
        [-0.4988,  1.5406,  0.7530,  1.1316]])


In [23]:
# In-place addition (change the value of r2)
r2.add_(r)
print(r2)

tensor([[ 0.7495,  0.1162,  1.9964,  0.8468],
        [ 1.3471,  1.5161,  0.0986,  1.7539],
        [ 2.0434,  0.8559,  2.5851, -0.7019],
        [-0.4988,  1.5406,  0.7530,  1.1316]])


In [24]:
print(r2[:, 1])
print(r2[:, 2])
print(r2[:3, :])
num_ten = r2[2, 3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([0.1162, 1.5161, 0.8559, 1.5406])
tensor([1.9964, 0.0986, 2.5851, 0.7530])
tensor([[ 0.7495,  0.1162,  1.9964,  0.8468],
        [ 1.3471,  1.5161,  0.0986,  1.7539],
        [ 2.0434,  0.8559,  2.5851, -0.7019]])
tensor(-0.7019)
-0.701934814453125
tensor([ 2.0434,  0.8559,  2.5851, -0.7019])


## **Numpy Bridge**

In [25]:
import numpy as np

In [26]:
# Converting a Torch Tensor to a Numpy Array
print(a)
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
# See how the numpy array changes in value when changing the tensor.
a.add_(1)
print(a)
print(b)

tensor([2, 2, 1])
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
# Converting NumPy Array to Torch Tensor
# See how changing the numpy array changed the Torch tensor automatically.
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
# Move the tensors to GPU if available
r2 = r2.to("mps")
print(r2)

tensor([[ 0.7495,  0.1162,  1.9964,  0.8468],
        [ 1.3471,  1.5161,  0.0986,  1.7539],
        [ 2.0434,  0.8559,  2.5851, -0.7019],
        [-0.4988,  1.5406,  0.7530,  1.1316]], device='mps:0')


In [29]:
# Provide Easy switiching between CPU and GPU
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
# Move tensors to the device
r2 = r2.to(device)
print(r2)

tensor([[ 0.7495,  0.1162,  1.9964,  0.8468],
        [ 1.3471,  1.5161,  0.0986,  1.7539],
        [ 2.0434,  0.8559,  2.5851, -0.7019],
        [-0.4988,  1.5406,  0.7530,  1.1316]], device='mps:0')


In [30]:
# Convert a list to a tensor
a = [1, 2, 3, 4]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[1, 2, 3, 4]
tensor([1, 2, 3, 4]) torch.int64


In [31]:
data = [[1., 2.], [3., 4.],
        [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## **Tensor Concatentation**

In [32]:
# Tensor Concatenation
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
# Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print (con_2)

tensor([[ 0.2779, -0.8845,  0.7244, -1.3629,  0.5005],
        [-0.3055, -1.9837, -0.2461, -0.0186,  1.5770]])
tensor([[-0.8788,  0.1098,  0.1634,  0.4407,  1.3317],
        [ 0.9222,  0.0857,  0.5767, -0.6149, -0.0301],
        [-0.0854,  1.1349, -0.3031,  1.1423,  1.6161]])


tensor([[ 0.2779, -0.8845,  0.7244, -1.3629,  0.5005],
        [-0.3055, -1.9837, -0.2461, -0.0186,  1.5770],
        [-0.8788,  0.1098,  0.1634,  0.4407,  1.3317],
        [ 0.9222,  0.0857,  0.5767, -0.6149, -0.0301],
        [-0.0854,  1.1349, -0.3031,  1.1423,  1.6161]])


tensor([[ 0.8603, -0.0544,  1.3501],
        [-0.9304,  1.3489,  0.2013]])
tensor([[-0.4311, -0.0126, -1.7152,  0.5761, -0.7085],
        [-1.8810, -0.1933, -0.3971,  0.3105,  0.9638]])


tensor([[ 0.8603, -0.0544,  1.3501, -0.4311, -0.0126, -1.7152,  0.5761, -0.7085],
        [-0.9304,  1.3489,  0.2013, -1.8810, -0.1933, -0.3971,  0.3105,  0.9638]])


## **Adding Dimensions to Tensors**

In [33]:
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1, 1)
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2, 3, 4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:, 2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c, 2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.2410, 0.8621, 0.3515, 0.9793],
         [0.8486, 0.2847, 0.2832, 0.4095],
         [0.3174, 0.5810, 0.4634, 0.1754]],

        [[0.7049, 0.5005, 0.4254, 0.6279],
         [0.0911, 0.9635, 0.8314, 0.7384],
         [0.3211, 0.4972, 0.9624, 0.6578]]])


tensor([[0.3515, 0.2832, 0.4634],
        [0.4254, 0.8314, 0.9624]])
torch.Size([2, 3])


tensor([[[0.3515],
         [0.2832],
         [0.4634]],

        [[0.4254],
         [0.8314],
         [0.9624]]])
torch.Size([2, 3, 1])


## **AutoGrad**

In [34]:
# If requires grad=True, the Tensor object keeps track of how it was created
x = torch.tensor([1., 2., 3.], requires_grad = True)
y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x + y
print(z)
print(z.grad_fn)
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [35]:
# Now perform backpropagation on s to compute the gradients with respect to x 
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [36]:
# By default, requires_grad is False
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't perform backpropagation through z
print(z.grad_fn)
# Another way to se the requires_grad = True
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as shown by grad_fn
z = x + y
print(z.grad_fn)
# If any input to an operation have `requires_grad=True`, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.requires_grad)
# z.detach() returns a new Tensor that shares the same storage as `z`, but with the computation history removed.
# It doesn't know anything about how it was computed. In other words, we have broken the Tensor away from its past history.

# You can also stop autograd from tracking history on Tensors.
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
False
True
True
False


In [37]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
