In [22]:
import torch

## **Torch Tensors**

In [23]:
# This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [24]:
# This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [25]:
# The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [26]:
# Get the number of rows of b
print(b.shape[0])

4


In [27]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do 
# c = torch.tensor([2,2,1], dtype=torch.double)

In [28]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do 
# d = torch.tensor([[2,2,1]], dtype=torch.double)

In [29]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [30]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [31]:
print(c.mean())

tensor(2.5833)


In [32]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [33]:
print(c.std())

tensor(1.5050)


In [34]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [35]:
# Reshape b
# Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
# Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
# We can reshape 3D tensors
print('\n')
# Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
three_dim = torch.rand(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12)) # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[0.0953, 0.1830, 0.4913, 0.8096],
         [0.2454, 0.3502, 0.9674, 0.0801],
         [0.5285, 0.8306, 0.7364, 0.5621]],

        [[0.7506, 0.7279, 0.5263, 0.3673],
         [0.5722, 0.0439, 0.7624, 0.0175],
         [0.0149, 0.9376, 0.7219, 0.5470]]])
tensor([[0.0953, 0.1830, 0.4913, 0.8096, 0.2454, 0.3502, 0.9674, 0.0801, 0.5285,
         0.8306, 0.7364, 0.5621],
        [0.7506, 0.7279, 0.5263, 0.3673, 0.5722, 0.0439, 0.7624, 0.0175, 0.0149,
         0.9376, 0.7219, 0.5470]])
tensor([[0.0953, 0.1830, 0.4913, 0.8096, 0.2454, 0.3502, 0.9674, 0.0801, 0.5285,
         0.8306, 0.

In [36]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.8450, 0.9595, 0.2483, 0.8395],
        [0.4750, 0.1337, 0.8475, 0.8378],
        [0.4390, 0.4905, 0.2968, 0.1492],
        [0.8626, 0.9725, 0.9851, 0.0438]])


In [37]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn (4,4)
print (r2)
print (r2.dtype)

tensor([[ 0.3181,  0.9964, -0.2442, -0.9310],
        [ 0.4602, -0.1118,  1.3136,  0.7709],
        [-0.4428,  0.4627,  0.4591,  0.1516],
        [-0.0556,  2.0429,  1.7112, -0.0656]])
torch.float32


In [38]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint (6,10, (5,))
print (in_array)
print (in_array.dtype)

tensor([8, 8, 6, 6, 8])
torch.int64


In [39]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print (in_array2)

tensor([[6, 7, 6],
        [9, 8, 7],
        [6, 7, 8]])


In [40]:
#Get the number of elemens in in_array
print(torch.numel(in_array))
#Get the number of elemens in in_array2
print(torch.numel(in_array2))

5
9


In [41]:
#Construct a 3x3 matrix of zeros and of atype long:
z = torch.zeros (3, 3, dtype=torch.long)
print (z)
#Construct a 3x3 matrix of ones
o = torch.ones (3,3)
print(o)
print (o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32
