In [1]:
import torch

## **Torch Tensors**

In [2]:
# This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
# This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [4]:
# The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
# Get the number of rows of b
print(b.shape[0])

4


In [6]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do 
# c = torch.tensor([2,2,1], dtype=torch.double)

In [7]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do 
# d = torch.tensor([[2,2,1]], dtype=torch.double)

In [8]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [9]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [10]:
print(c.mean())

tensor(2.5833)


In [11]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [12]:
print(c.std())

tensor(1.5050)


In [13]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [14]:
# Reshape b
# Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
# Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
# We can reshape 3D tensors
print('\n')
# Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
three_dim = torch.rand(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12)) # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[0.3278, 0.1131, 0.5119, 0.5395],
         [0.2847, 0.9405, 0.5078, 0.0988],
         [0.7394, 0.7099, 0.7101, 0.0595]],

        [[0.4063, 0.3102, 0.4413, 0.9169],
         [0.1366, 0.7752, 0.2778, 0.9767],
         [0.3461, 0.1725, 0.0485, 0.6762]]])
tensor([[0.3278, 0.1131, 0.5119, 0.5395, 0.2847, 0.9405, 0.5078, 0.0988, 0.7394,
         0.7099, 0.7101, 0.0595],
        [0.4063, 0.3102, 0.4413, 0.9169, 0.1366, 0.7752, 0.2778, 0.9767, 0.3461,
         0.1725, 0.0485, 0.6762]])
tensor([[0.3278, 0.1131, 0.5119, 0.5395, 0.2847, 0.9405, 0.5078, 0.0988, 0.7394,
         0.7099, 0.

In [15]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.9222, 0.2135, 0.6690, 0.2335],
        [0.1526, 0.7948, 0.9463, 0.5578],
        [0.3615, 0.5642, 0.7821, 0.3140],
        [0.1949, 0.6545, 0.1357, 0.3464]])


In [16]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn (4,4)
print (r2)
print (r2.dtype)

tensor([[ 0.2051, -0.0166,  0.4000,  0.8712],
        [ 0.7407,  0.6119,  0.4413, -0.1182],
        [ 1.2079,  0.8610, -0.0649,  0.6437],
        [ 0.6909, -0.9505,  0.0286,  0.3797]])
torch.float32


In [17]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint (6,10, (5,))
print (in_array)
print (in_array.dtype)

tensor([9, 6, 8, 8, 9])
torch.int64


In [18]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print (in_array2)

tensor([[6, 8, 9],
        [7, 9, 8],
        [7, 9, 7]])


In [19]:
#Get the number of elemens in in_array
print(torch.numel(in_array))
#Get the number of elemens in in_array2
print(torch.numel(in_array2))

5
9


In [20]:
#Construct a 3x3 matrix of zeros and of atype long:
z = torch.zeros (3, 3, dtype=torch.long)
print (z)
#Construct a 3x3 matrix of ones
o = torch.ones (3,3)
print(o)
print (o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [21]:
r2_like = torch.randn_like(r2, dtype=torch.double)  # Convert the data type of the tensor to double
print(r2_like)

tensor([[ 1.4698, -0.5719, -0.7640, -0.9656],
        [ 0.3580, -1.4332, -0.4482, -0.6924],
        [ 0.4664,  0.3573,  0.8312, -2.7705],
        [ 0.7409, -2.6271, -0.7876, -0.4953]], dtype=torch.float64)


In [22]:
# Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 1.1273,  0.1969,  1.0689,  1.1047],
        [ 0.8934,  1.4067,  1.3876,  0.4396],
        [ 1.5695,  1.4252,  0.7173,  0.9577],
        [ 0.8857, -0.2960,  0.1642,  0.7262]])


In [23]:
# In-place addition (change the value of r2)
r2.add_(r)
print(r2)

tensor([[ 1.1273,  0.1969,  1.0689,  1.1047],
        [ 0.8934,  1.4067,  1.3876,  0.4396],
        [ 1.5695,  1.4252,  0.7173,  0.9577],
        [ 0.8857, -0.2960,  0.1642,  0.7262]])


In [24]:
print(r2[:, 1])
print(r2[:, 2])
print(r2[:3, :])
num_ten = r2[2, 3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([ 0.1969,  1.4067,  1.4252, -0.2960])
tensor([1.0689, 1.3876, 0.7173, 0.1642])
tensor([[1.1273, 0.1969, 1.0689, 1.1047],
        [0.8934, 1.4067, 1.3876, 0.4396],
        [1.5695, 1.4252, 0.7173, 0.9577]])
tensor(0.9577)
0.9577056169509888
tensor([1.5695, 1.4252, 0.7173, 0.9577])


## **Numpy Bridge**

In [25]:
import numpy as np

In [26]:
# Converting a Torch Tensor to a Numpy Array
print(a)
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
# See how the numpy array changes in value when changing the tensor.
a.add_(1)
print(a)
print(b)

tensor([2, 2, 1])
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
# Converting NumPy Array to Torch Tensor
# See how changing the numpy array changed the Torch tensor automatically.
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
# Move the tensors to GPU if available
r2 = r2.to("mps")
print(r2)

tensor([[ 1.1273,  0.1969,  1.0689,  1.1047],
        [ 0.8934,  1.4067,  1.3876,  0.4396],
        [ 1.5695,  1.4252,  0.7173,  0.9577],
        [ 0.8857, -0.2960,  0.1642,  0.7262]], device='mps:0')


In [29]:
# Provide Easy switiching between CPU and GPU
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
# Move tensors to the device
r2 = r2.to(device)
print(r2)

tensor([[ 1.1273,  0.1969,  1.0689,  1.1047],
        [ 0.8934,  1.4067,  1.3876,  0.4396],
        [ 1.5695,  1.4252,  0.7173,  0.9577],
        [ 0.8857, -0.2960,  0.1642,  0.7262]], device='mps:0')


In [30]:
# Convert a list to a tensor
a = [1, 2, 3, 4]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[1, 2, 3, 4]
tensor([1, 2, 3, 4]) torch.int64


In [31]:
data = [[1., 2.], [3., 4.],
        [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## **Tensor Concatentation**

In [32]:
# Tensor Concatenation
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
# Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print (con_2)

tensor([[ 0.0186,  0.6458,  3.2988, -0.8091, -1.2574],
        [ 1.1570, -2.3473, -0.6816, -0.5101,  0.3776]])
tensor([[-0.1449,  1.5311, -0.7076, -0.6393, -0.7781],
        [ 1.0818, -0.3629, -0.6996,  0.2477,  0.1371],
        [-0.2167, -1.2853,  0.8649, -0.9924,  1.7282]])


tensor([[ 0.0186,  0.6458,  3.2988, -0.8091, -1.2574],
        [ 1.1570, -2.3473, -0.6816, -0.5101,  0.3776],
        [-0.1449,  1.5311, -0.7076, -0.6393, -0.7781],
        [ 1.0818, -0.3629, -0.6996,  0.2477,  0.1371],
        [-0.2167, -1.2853,  0.8649, -0.9924,  1.7282]])


tensor([[-0.9084, -0.5255, -0.2908],
        [-0.5898, -0.9214,  1.5160]])
tensor([[ 0.4948,  0.8339,  1.1041, -0.5026, -1.2272],
        [-0.6487,  0.9023,  1.0157,  0.0228, -0.5433]])


tensor([[-0.9084, -0.5255, -0.2908,  0.4948,  0.8339,  1.1041, -0.5026, -1.2272],
        [-0.5898, -0.9214,  1.5160, -0.6487,  0.9023,  1.0157,  0.0228, -0.5433]])


## **Adding Dimensions to Tensors**

In [33]:
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1, 1)
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2, 3, 4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:, 2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c, 2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.7767, 0.3574, 0.3936, 0.6893],
         [0.1035, 0.5994, 0.2025, 0.7283],
         [0.0020, 0.2448, 0.5143, 0.4157]],

        [[0.9302, 0.3296, 0.4638, 0.7740],
         [0.5089, 0.5676, 0.6996, 0.3749],
         [0.2704, 0.5375, 0.3203, 0.6636]]])


tensor([[0.3936, 0.2025, 0.5143],
        [0.4638, 0.6996, 0.3203]])
torch.Size([2, 3])


tensor([[[0.3936],
         [0.2025],
         [0.5143]],

        [[0.4638],
         [0.6996],
         [0.3203]]])
torch.Size([2, 3, 1])


## **AutoGrad**

In [34]:
# If requires grad=True, the Tensor object keeps track of how it was created
x = torch.tensor([1., 2., 3.], requires_grad = True)
y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x + y
print(z)
print(z.grad_fn)
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [35]:
# Now we can perform backpropagation on s to compute the gradients with respect to x 
s.backward()
print(x.grad)

tensor([1., 1., 1.])
