In [1]:
import torch
import torch.nn as nn

In [2]:
layer = nn.Linear(5, 5)
layer.weight

Parameter containing:
tensor([[-0.0034, -0.2879,  0.1215,  0.0689, -0.0109],
        [ 0.0510, -0.3841, -0.0685,  0.1933, -0.1983],
        [-0.3423, -0.2345, -0.2304,  0.1604, -0.1044],
        [ 0.0686, -0.0478, -0.1117,  0.3649,  0.0893],
        [ 0.0175,  0.0641, -0.4446, -0.3042, -0.2042]], requires_grad=True)

In [3]:
nn.init.uniform_(layer.weight, a = 0, b = 3)

Parameter containing:
tensor([[0.5426, 0.1250, 2.0567, 0.9067, 1.1176],
        [1.8993, 1.1498, 1.3064, 1.0142, 1.8749],
        [1.6290, 0.3884, 2.1448, 0.3353, 1.0354],
        [1.6974, 1.4443, 0.9542, 1.1262, 2.9017],
        [1.2357, 0.9489, 0.3279, 0.8053, 1.0136]], requires_grad=True)

In [4]:
print(nn.init.normal_(layer.weight, mean = 0, std = 1))
print('\n')
print(nn.init.normal_(layer.weight, mean = 0, std = 0.2))

Parameter containing:
tensor([[ 0.7660,  0.4352, -0.6254, -1.6586, -0.9708],
        [ 0.1429,  0.7659,  0.5106,  0.2760,  0.1854],
        [-2.1652,  1.1644, -0.0348, -1.3283, -1.4728],
        [ 0.9639, -0.8104,  1.2031,  1.7540,  1.7041],
        [-0.2749, -0.0754,  0.0785, -0.4280,  0.4181]], requires_grad=True)


Parameter containing:
tensor([[ 0.3195,  0.0653, -0.1026, -0.2240, -0.4344],
        [ 0.1507,  0.2044,  0.0798, -0.0031,  0.2215],
        [ 0.0764,  0.0253, -0.2105,  0.1528,  0.0479],
        [-0.3089,  0.2489,  0.3572, -0.1990, -0.3635],
        [-0.2028, -0.0006,  0.0790, -0.0964, -0.1991]], requires_grad=True)


In [5]:
nn.init.constant_(layer.bias, 0) # sets all biases to zero
print(layer.bias)

print('\n')

nn.init.zeros_(layer.bias) # sets all biases to zero
print(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)


Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)


In [6]:
print(nn.init.xavier_uniform_(layer.weight, gain = 1))
print('\n')
print(nn.init.xavier_normal_(layer.weight, gain = 1))

Parameter containing:
tensor([[-0.3395,  0.4426, -0.7669, -0.3658, -0.6984],
        [ 0.7542, -0.1772, -0.1406, -0.4852,  0.1536],
        [-0.3242, -0.0652, -0.3483,  0.3278, -0.0401],
        [ 0.5698, -0.2535,  0.0954,  0.6404,  0.4474],
        [ 0.1944, -0.1958,  0.5120, -0.5189, -0.0029]], requires_grad=True)


Parameter containing:
tensor([[ 0.6482, -0.7645,  0.5582,  0.1863, -0.4184],
        [-0.1097,  0.0263,  0.0173, -0.0034,  0.3372],
        [-0.4293, -0.6537,  0.0124, -0.4684,  0.6690],
        [-0.0330, -0.0451, -0.2195, -0.7654, -0.7790],
        [-0.3963, -0.7183, -0.3447,  0.0203,  0.6359]], requires_grad=True)
